### ISSUE TITLE
Tectonic no longer compatible with NeoForge 1.21.0 (21.0.167)

### ISSUE THREAD

**Issue by NovaViper** [Apollounknowndev/tectonic#200]
The newest version of Tectonic (v2.4.1a) now requires NeoForge 21.1.12, which is only available on Minecraft 1.21.1 and not 1.21.0. This version completely breaks compatibility with 1.21.0, as its last version of NeoForge is 21.0.167.

**Comment by desagas** [comment]
I was so very sad to see this. I kept it on the previous version so I could keep it installed.

**Comment by Apollounknowndev** [comment]
WAI; previous versions of Tectonic had to port a Fabric feature to Neoforge to allow both versions to function properly. Neoforge 21.1.12 added that feature to the modloader itself which Tectonic is now relying on. Marking the new version as Neoforge 1.21.0 was an oversight on my part that I've now fixed.

**Comment by NovaViper** [comment]
@Apollounknowndev Hey can you edit the supported versions of the file that's up on Modrinth and CurseForge? PrismLauncher (and most likely CurseForge launcher) is still seeing v2.4.1a as a version that's compatible with 1.21.0, thus it tries to download it even though it's not compatible with 1.21 anymore.

**Comment by desagas** [comment]
@NovaViper I don't know if this will help you at all, but, in my pack dev, I just copied and pasted every single mod in my 1.21 folder to my 1.21.1 folder, over 200 mods, and every single one loaded correctly without error. I have everything from this and other biome mods, to mob mods, to dimension mods, etc. No bugs yet.

**Comment by NovaViper** [comment]
@desagas Hey thanks! I can manually download the old version with PrismLauncher but the issue becomes that PrismLauncher wants to download the latest version (which will eventually become annoying to make sure to exclude Tectonic from the updater especially when many mods update all at once)
